spring.application.name=cp2

server.port=8080

spring.datasource.url=jdbc:h2:mem:meetingdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin123
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

jwt.secret=minhaChaveSecretaMuitoLongaParaJWT2024ApiSalasReuniao
jwt.expiration=86400000

logging.pattern.console=%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.level.com.api.meetingroom=DEBUG

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.packagesToScan=com.example.cp2.controller
springdoc.swagger-ui.disable-swagger-default-url=true